participant:
    resource: "@ParticipantBundle/Controller/"
    type:     annotation
    prefix:   /participant

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

coresphere_console:
    resource: .
    type: extra