<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentTypeRepository extends EntityRepository
{
    public function queryFindAllEquipmentType()
    {
        $em = $this
            ->getEntityManager();

        $query = $em ->createQueryBuilder()
            ->select('et')
            ->from('AdminBundle:EquipmentType', 'et');

        return $query;
    }
}
