<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * requestResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class requestResponseRepository extends EntityRepository
{
}
