<?php

namespace ParticipantBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AdminBundle\Entity\Equipment;
/**
 * bringedEquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bringedEquipmentRepository extends EntityRepository
{
    public function findAllBringedEquipmentSum()
    {
        $em = $this
            ->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('SUM(b.quantity) as quantity')
            ->from('ParticipantBundle:bringedEquipment', 'b')
            ->leftJoin('b.equipment', 'e')
            ->groupBy('e.platform', 'e.equipmentType');


        return $result = $query->getQuery()->getResult();

    }
}
